adding files
shirinnikita/ask_me pull request #1
Opened 2016-11-21 19:20 UTC by shirinnikita

2016-11-21 19:46 UTC, aakogtenkov requested changes

2016-11-21 19:46 UTC, aakogtenkov commented on lab-01.py
> +BUTCH_SIZE = 100
Мне казалось, что пишется batch. Вроде бы Яндекс со мной согласен)

2016-11-21 19:46 UTC, aakogtenkov commented on lab-01.py
> +    temp = np.exp(np.multiply(-Y, X.dot(w)))
есть ощущение, что что-то может пойти не так при достаточно большом значении -Y * wX. Даже у Питона есть верхняя граница значений чисел.

2016-11-21 19:46 UTC, aakogtenkov commented on lab-01.py
> +    e_dw = 0
Не очень понятно, что это за 2 последние переменные. Я бы попробовал сделать названия чуть понятнее. Да, в Adadelta довольно много формул и не очень понятно, как называть по-человечески некоторые вещи, но вдруг получится придумать название получше.

2016-11-21 19:46 UTC, aakogtenkov commented on lab-01.py
> +    diag_G = np.copy(w)
Возможно, стоило назвать не "диагональ G", а как-то более конкретно указывая на то, что там хранится - что-то в роде средней суммы квадратов градиентов. Но тут дело касается математических формул, так что на усмотрение Дениса. Я сам не очень представляю, как лучше назвать это.
Если менять, то к diag_G выше это тоже относится.

2016-11-21 19:46 UTC, aakogtenkov commented on lab-01.py
> +            momentum_s = momentum / (1 - gamma2_t)
Не очень понятно, что означает _s на конце. Мне кажется, лучше сделать чуть другое название. Вроде в статьях название встречалось.

2016-11-21 19:46 UTC, aakogtenkov commented on lab-01.py
> +# На тех же данных обычный спуск делает 14 шагов, наискорейший - 3. Благодаря тому, что для нашей метрики существует явное решение задачи линейной оптимизации, с каждым шагом мы эффективно приближаем
А можно отрисовывать прямые на одной картинке? Так было бы нагляднее. Также было бы здорово добавить прямую, отображающую точное решение (в задании вроде это говорится).

2016-11-24 17:02 UTC, aakogtenkov requested changes
Ну вроде бы больше каких-то недочетов, которые могут броситься в глаза, нет. Мне по-прежнему не очень нравятся некоторые названия переменных, связанных с математическими формулами, но поскольку я сам не знаю, как хорошо их назвать, то и не буду критиковать. 
Вообще, этот код выглядит лучше моего кода, поэтому тяжело искать недочеты))

2016-11-24 17:02 UTC, aakogtenkov commented on lab-01.py
> +    w = np.zeros(785)
Мне кажется, константу 785 стоит ввести еще не этапе считывания выборки, это было бы логично. А то у тебя не только в этой функции встречается это число

2017-03-19 22:25 UTC, dasimagin reviewed
Проверил, заливай в мастер.

2017-03-19 22:25 UTC, dasimagin commented on lab-01.py
> +def make_two_clusters(SIGMA, AXIS_RANGE, CLUSTER_SIZE):
Что касается переменных, то в питоне принято их писать с маленькой буквы и использовать '_' в качестве разделителя. Стиль ONLY_UPPERCASE обычно используют для каких-то глобальных констант.

2017-03-19 22:25 UTC, dasimagin commented on lab-01.py
> +    clusterPlus = np.append(np.random.normal(AXIS_RANGE / 3, SIGMA, (CLUSTER_SIZE, 2)), ones_column, axis=1)
В numpy есть и многомерное распределение. Просто у тебя центры облачков всегда по диагонали лежат.

2017-03-19 22:25 UTC, dasimagin commented on lab-01.py
> +    trans_X = X.transpose()
Обычно пишут X_trans

2017-03-19 22:25 UTC, dasimagin commented on lab-01.py
> +    plt.plot([-AXIS_RANGE, AXIS_RANGE], [(AXIS_RANGE * w[1] + w[2])/w[0], (-AXIS_RANGE * w[1] + w[2])/w[0]],
Это неверное задание прямой.

2017-03-19 22:25 UTC, dasimagin commented on lab-01.py
> +def draw_path(path, function=None, marker_shape, line_color, titlesOn = True):
Так нельзя, чтобы после аргументов, у которых есть значение по умолчанию, шли аргументы без него.

2017-03-19 22:25 UTC, dasimagin commented on lab-01.py
> +fig = plt.figure()
моя версия библиотеки не смогла отрисовать :(

2017-03-19 22:25 UTC, dasimagin commented on lab-01.py
> +        grad = count_grad(currentPosition - step)
у меня там опечатка в конспекте была - LMBD * step

2017-03-19 22:25 UTC, dasimagin commented on lab-01.py
> +        while temp_position + BATCH_SIZE < len(train_set):
кажется, что более традиционно делать немного по другому. У нас есть цикл, которые итерируется по батчам, но внутри мы проверяем критерий остановки.

2017-03-19 22:25 UTC, dasimagin commented on lab-01.py
> +    return len(test_set) - guessed
Относительная ошибка дает больше информации.

2017-03-19 22:25 UTC, dasimagin commented on lab-01.py
> +    #anti-overflow
я рассказывал, как с этим можно бороться по другому.

2017-03-19 22:25 UTC, dasimagin commented on lab-01.py
> +    linearCoefficient = np.sum(np.dot(np.dot(X, grad.transpose()), np.dot(X, w.transpose()) - Y)) / np.sum(np.square(np.dot(X, grad.transpose())))
все правильно сделал!

2017-03-19 22:25 UTC, dasimagin commented on lab-01.py
> +        while temp_position + BATCH_SIZE < len(train_set):
очень все медленно учится.. боюсь есть проблема с эффективностью написания кода + многие операции можно сделать матричными.

2017-06-01 18:05 UTC, closed without merging