Lab04
shirinnikita/ask_me pull request #3
Opened 2017-03-03 18:56 UTC by shirinnikita

Hello guys,
please help me to make something good out of my lab-04

2017-03-03 23:03 UTC, mryab requested changes
Пока что так, но ещё необходимо добавить недостающие части работы

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +import random
Для воспроизводимости добавь сиды для всех используемых генераторов случайных чисел (системный, TensorFlow, NumPy - его использует sklearn)

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +    output = open('./wiki_text_dump_4.txt', 'w')
Тут точно должно быть 4? Получается, он пишет в файл, который потом не используется

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +# Для выполнения первого задания воспользуемся библиотечными функциями. Для парсинга википедии(у меня ее simple-вариант, около 80К статей после парсинга) я использовал фукнции библиотеки gensim, но н
Ну проект у нас вроде на 3 питоне, так что стоило бы попытаться сделать так, чтобы всё на нём заработало :)

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +        text = [w for w in text if w in voc]
А это точно работает? get_texts() выдаёт байтовые токены, так что все проверки вида `w in voc` не срабатывают и выходит пустой файл (hint: `decode` поможет обуздать эту проблему)

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +dump = open('wiki_text_dump.txt', 'r')
Вообще говоря, нам точно нужно постоянно вот так сохранять-загружать файлы? Если ты экономишь память, то я не вижу `del`, а иначе только время тратится. Ещё я не заметил close() у открываемых файлов

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +np.save('lsa1', lsa_embedding)
См. комментарий про файлы

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +embedding_size = 200
В задании было «достаточно 256», ну да ладно, это можно проинтерпретировать по-разному

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +num_steps = 10000000
Как-то слишком много эпох, у меня модель неплохо обучилась на в 10 раз меньшем количестве

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +batch, labels = get_batch(batch_size=200, num_skips=8, skip_window=4)
А это не сдвинуло data_index?

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +np.save('w2v2', w2v_embedding)
См. комментарий выше про файлы

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +analogy_k_nearest('king', 'man', 'women', lsa_embedding, 10, 'cosine')
Ты, во-первых, проверяешь не на том эмбеддинге, а во-вторых, ещё надо проверить для тех 30 слов, которые ты привёл раньше

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +# Сложность при использования негатив сэмплинга это $embedding\_size \times NEG\_SMPLS \times num\_steps$
А размер контекста и корпуса в формуле отсутствуют? И перепиши с теми обозначениями, которые в лабе были даны

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +np.save('glove_f', glove_embedding)
См. комментарий про файлы

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +        ret.append(inverted_dict[i])
Перепиши цикл в виде list comprehension

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +questions = open('questions-words.txt', 'r')
Перепиши в виде `with open … as …`

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +        print(question.lower(), file=questions_2, end='')
Зачем ещё один новый файл, если можно в памяти держать?

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +print("                                                                     |%5d|%5d|%5d|%5d|%5d|%5d|" % (lsa_cos_score,
Всё красиво, но на гитхабе не влезает по ширине. Мб, сделать ячейки поуже?

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +questions = open('quest_list.txt', 'r')
`with open … as …`

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +        if word in direct_dict.keys() and word not in already_added:
Если проверяешь на наличие, то лучше использовать `set`

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +del ax, fig
Удаляются ещё до объявления?

2017-03-03 23:03 UTC, mryab commented on shirin_l4.py
> +        already_added.index(word)
А это точно нужная строка? Результат же нигде не используется

2017-03-04 07:56 UTC, mryab commented on shirin_l4.py
> +    tf.initialize_all_variables().run()
`WARNING:tensorflow:From <ipython-input-69-38d746dc1320>:2 in <module>.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.`

2017-03-08 21:51 UTC, shirinnikita commented on shirin_l4.py
> +        if word in direct_dict.keys() and word not in already_added:
Мне тут важен порядок, а поиск по 80-элементому листу все равно работает за 0

2017-03-08 21:55 UTC, shirinnikita commented on shirin_l4.py
> +print("                                                                     |%5d|%5d|%5d|%5d|%5d|%5d|" % (lsa_cos_score,
Никак( они шириной в самое длинное слово

2017-03-08 21:56 UTC, shirinnikita commented on shirin_l4.py
> +        print(question.lower(), file=questions_2, end='')
Для наглядности, он же лежит в репозитории

2017-03-09 11:51 UTC, mryab commented on shirin_l4.py
> +print("                                                                     |%5d|%5d|%5d|%5d|%5d|%5d|" % (lsa_cos_score,
Ну галочки и крестики-то точно можно окружить одним пробелом, а не двумя. Вот и выйдет неплохая экономия места!

2017-03-09 12:21 UTC, mryab requested changes
Уже получше, но малость отшлифовать стоит + вопрос с асимптотиками остаётся открытым

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +    output = open('./wiki_text_dump.txt', 'w')
`with open … as …`

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +dump = open('wiki_text_dump.txt', 'r')
`with open … as …`

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +dump = open('wiki_text_dump.txt', 'r')
`with open … as …`

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +questions = open('quest_list.txt', 'r')
`with open … as …`

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +to_tsne = open('to_tsne.txt', 'r')
`with open … as …`

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +        text = [w for w in text if w in voc]
Опять создаётся пустой файл :cry:

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +dump = open('wiki_text_dump.txt', 'r')
А ещё ты мог наполнить data ещё при предыдущем открытии файла

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +        if word in direct_dict.keys():
Точно эффективно каждый раз вызывать метод и получать СПИСОК ключей словаря? У тебя же уже создавался `set`, да и в файл ты записал только встречающиеся в словаре слова

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +from sklearn.preprocessing import Normalizer
Не используется

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +from sklearn.feature_extraction.text import TfidfTransformer
Не используется

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +from random import randint
Вот ты импортируешь `randint`, но используешь всё равно `random.randint`

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +from nltk.corpus import stopwords
Три модуля выше не используются

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +direct_dict = tfidf_maker.vocabulary_
Ещё один словарь? А `wiki.dictionary` куда делся?

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +# Перепишем функцию поиска ближайшего слова так, чтобы она не выводила результат, а просто возвращала его.
Не проще ли тогда оставить возвращающую результат функцию, а печатать только там, где надо?

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +    questions_2 = open('quest_list.txt', 'w')
`with open … as …`

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +        print("  \033[1;32;0m✓\033[0m  |", end='')
Страшные форматные строки. Запихни их хотя бы в константы тогда

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +        print(" " * 68,"|lsa,c|lsa,e|w2v,c|w2v,e|glv,c|glv,e|")
Да и вообще мне кажется, что нам не так интересно смотреть, какое конкретно слово одна модель угадывает, а остальные нет, поэтому можно убрать все принты и просто в конце вывести результат

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +            if word in direct_dict.keys() and word not in added_words:
Что-то я не вижу, чтобы тебе был нужен порядок, а для большого списка всё-таки поиск будет работать не за константу. Что, если я захочу построить t-SNE для всей Википедии, к примеру?

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +# Сложность при использования негатив сэмплинга $O(k  \times d  \times batch\_size  \times num\_steps)$
А где асимптотика для skip-gram?

2017-03-09 12:21 UTC, mryab commented on shirin_l4.py
> +# Сложность модели оценить сложно - понятно, что она линейная от числа ненулевых элементов матрицы X, линейная от размерности векторов-представлений (т.к. за шаг мы обновляем по одному представлению
Для всего, кроме числа ненулевых элементов, асимптотику посчитать вполне реально

2017-03-15 17:28 UTC, shirinnikita commented on shirin_l4.py
> +        print(" " * 68,"|lsa,c|lsa,e|w2v,c|w2v,e|glv,c|glv,e|")
Я хотел посмотреть(

2017-03-15 17:28 UTC, shirinnikita commented on shirin_l4.py
> +# Перепишем функцию поиска ближайшего слова так, чтобы она не выводила результат, а просто возвращала его.
Конечно, это лучше, но не думаю, что критично - просто мне было интересно и на расстояния посмотреть, а теперь мне это совсем стало не интересно, с листами пар не хочу дела иметь)

2017-03-15 17:28 UTC, shirinnikita commented on shirin_l4.py
> +# Сложность при использования негатив сэмплинга $O(k  \times d  \times batch\_size  \times num\_steps)$
В смысле когда мы обычный софтмакс используем? Внизу написал "т.к. в наивной реализации они в итоге дают размер матрицы  W×dW×d , что очень затратно", как-то расписать?

2017-03-15 17:28 UTC, shirinnikita commented on shirin_l4.py
> +        if word in direct_dict.keys():
Крыша едет

2017-03-15 17:28 UTC, shirinnikita commented on shirin_l4.py
> +dump = open('wiki_text_dump.txt', 'r')
В рамках предыдущего задания, между ними большие промежутки?)

2017-03-15 17:29 UTC, shirinnikita commented on shirin_l4.py
> +direct_dict = tfidf_maker.vocabulary_
Так это скрипт для парсинга, он как бы работал где-то за неделю до использования блокнота по назначению, выдал то, что от него требовалось - plain_text.txt, и больше его не нужно вспоминать) В памяти он уже подавно не висит. Вроде бы норм

2017-03-15 17:33 UTC, shirinnikita commented on shirin_l4.py
> +            if word in direct_dict.keys() and word not in added_words:
Но я же для маленькой части делаю, чтобы просто глянуть на нее, мне не нужна вся вики. Понятно, что если бы была идея построить для всей - то оптимизировал бы, но у меня 1К слов и рисуются вообще пара десятков
А зачем мне порядок - если я добавляю слова в added_words и в матрицу для скармливания t-SNE в одном порядке, то они как бы залинкованы - i-ый элемент added_words соответствует i-ой строке матрицы

2017-03-15 20:26 UTC, mryab commented on shirin_l4.py
> +direct_dict = tfidf_maker.vocabulary_
Подразумевается, что за один запуск ноутбука у нас будет выполнен весь код лабы, иначе зачем вообще в одном файле его держать?

2017-03-15 20:30 UTC, mryab commented on shirin_l4.py
> +dump = open('wiki_text_dump.txt', 'r')
Прав, в принципе

2017-03-15 20:37 UTC, mryab commented on shirin_l4.py
> +# Сложность при использования негатив сэмплинга $O(k  \times d  \times batch\_size  \times num\_steps)$
Ну если приписать хотя бы, что за наивная реализация, то норм, думаю

2017-03-15 20:41 UTC, mryab commented on shirin_l4.py
> +        print(" " * 68,"|lsa,c|lsa,e|w2v,c|w2v,e|glv,c|glv,e|")
Выглядит круто, конечно, но не когда треть ноутбука занимает, блин. Вот это уже можно точно в отдельный файл запихать тогда, если хочешь оставить c:

2017-03-15 21:07 UTC, mryab approved these changes
Остались уже по большей части косметические вещи, так что если за написанным именно таким образом кодом стоит какая-то скрытая логика, то откомменти, и можно будет не фиксить. Про перегон туда-обратно в файлы я не заметил как-то в прошлый раз, каюсь

2017-03-15 21:07 UTC, mryab commented on shirin_l4.py
> +metrics_comparison('moscow', lsa_embedding, 10)
Ещё кое-что: если у тебя функции тупо печатают таблички, то можно подсократить код: загони все слова в список и вызови metrics_comparison для всех слов в нём. Тогда на это занята будет только одна ячейка для каждого эмбеддинга

2017-03-15 21:07 UTC, mryab commented on shirin_l4.py
> +w2v_embedding = np.load('w2v.npy')
В чём идея сохранения и потом сразу же загрузки матрицы в одну и ту же переменную? Понятно ещё, что когда тестируешь алгоритмы, стоит как-то сохранять, но в готовой-то лабе можно и убрать. Или у тебя в память всё одновременно не влезает?

2017-03-15 21:07 UTC, mryab commented on shirin_l4.py
> +X = sparse.lil_matrix((vocabulary_size, vocabulary_size), dtype=np.float64)
В качестве способа экономии памяти можно сделать как минимум `float32`

2017-03-15 21:07 UTC, mryab commented on shirin_l4.py
> +glove_embedding = np.load('glove.npy')
Тот же вопрос, что и с w2v

2017-03-15 21:07 UTC, mryab commented on shirin_l4.py
> +                print(question.lower(), file=questions_2, end='')
Опять же, тут можно без файла обойтись, список вопросов короткий ведь

2017-03-15 21:07 UTC, mryab commented on shirin_l4.py
> +            added_words.index(word)
А эта строка что-то делает вообще?

2017-03-15 21:07 UTC, mryab commented on shirin_l4.py
> +                to_tsne_matrix = np.append(to_tsne_matrix, [glove_embedding[direct_dict[word]]], axis=0)
А ещё мне кажется, что проканало бы нечто проще, вроде 
`to_tsne_matrix=np.array([glove_embedding[direct_dict[word]] for word in words])`, и не пришлось бы тогда городить все эти махинации с `append` (проверку на наличие слова в словаре можно тогда перенести в часть кода с первичной обработкой файла)
Или вообще `to_tsne_matrix=glove_embedding[direct_dict[words]]`, но тут я уже не уверен, что сработает

2017-06-01 18:05 UTC, closed without merging